/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_walterreyes;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Examen1_WalterReyes extends javax.swing.JFrame {

    /**
     * Creates new form Examen1_WalterReyes
     */
    public Examen1_WalterReyes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_armas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        daño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Botón_arma = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Botón_Masculino = new javax.swing.JRadioButton();
        Botón_Femenino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb_armas_personas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Botón_Campista = new javax.swing.JRadioButton();
        Botón_Jason = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Botón_Supervisor = new javax.swing.JRadioButton();
        Botón_Normal = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Botón_Vivo = new javax.swing.JRadioButton();
        Botón_Desaparecido = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Desaparecidos = new javax.swing.JTextField();
        Botón_Guardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ver_Armas = new javax.swing.JTextArea();
        Posición_Armas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Botón_Editar_Arma = new javax.swing.JButton();
        Botón_Eliminar_Arma = new javax.swing.JButton();
        Botón_ver_armas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ver_Personas = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        Posición = new javax.swing.JTextField();
        Editar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        jLabel12.setText("Personas desaparecidas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de arma");

        cb_armas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hacha", "Pistola", "Bate", "Pala", "Sierra eléctica", "puños" }));

        jLabel2.setText("Porcentaje de daño: ");

        daño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dañoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("¿Porque todos tienen un arma? Esto es América");

        Botón_arma.setText("Agregar");
        Botón_arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_armaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(cb_armas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(daño, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(Botón_arma))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_armas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botón_arma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Crear Armas", jPanel1);

        jLabel4.setText("Nombre");

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        jLabel5.setText("Edad");

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo");

        buttonGroup1.add(Botón_Masculino);
        Botón_Masculino.setText("M");

        buttonGroup1.add(Botón_Femenino);
        Botón_Femenino.setText("F");

        jLabel7.setText("Armas");

        cb_armas_personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_armas_personasActionPerformed(evt);
            }
        });

        jLabel8.setText("TIpo de persona");

        buttonGroup2.add(Botón_Campista);
        Botón_Campista.setText("Campista");

        buttonGroup2.add(Botón_Jason);
        Botón_Jason.setText("Jason");

        jLabel9.setText("Tipo campista");

        buttonGroup3.add(Botón_Supervisor);
        Botón_Supervisor.setText("Supervisor");

        buttonGroup3.add(Botón_Normal);
        Botón_Normal.setText("Normal");

        jLabel10.setText("Estado de campista");

        buttonGroup4.add(Botón_Vivo);
        Botón_Vivo.setText("Vivo");

        buttonGroup4.add(Botón_Desaparecido);
        Botón_Desaparecido.setText("Desaparecido");

        jLabel11.setText("Jason");

        jLabel13.setText("Cantidad de personas que desapareció: ");

        Desaparecidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesaparecidosActionPerformed(evt);
            }
        });

        Botón_Guardar.setText("Guardar");
        Botón_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Nombre)
                                                .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Botón_Masculino)
                                                .addGap(18, 18, 18)
                                                .addComponent(Botón_Femenino))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(cb_armas_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(257, 257, 257)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botón_Campista)
                                    .addComponent(Botón_Supervisor)
                                    .addComponent(Botón_Vivo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Botón_Normal)
                                    .addComponent(Botón_Desaparecido)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Botón_Jason, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Desaparecidos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(Botón_Guardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Botón_Masculino)
                    .addComponent(Botón_Femenino))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_armas_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Botón_Campista, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botón_Jason)
                    .addComponent(jLabel13)
                    .addComponent(Desaparecidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Botón_Supervisor)
                    .addComponent(Botón_Normal))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Botón_Vivo)
                    .addComponent(Botón_Desaparecido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botón_Guardar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Crear Personas", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver_Armas.setEditable(false);
        Ver_Armas.setColumns(20);
        Ver_Armas.setRows(5);
        jScrollPane1.setViewportView(Ver_Armas);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 11, 358, 197));
        jPanel3.add(Posición_Armas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, -1));

        jLabel14.setText("Colocar Posición a editar");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));
        jPanel3.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        Botón_Editar_Arma.setText("Editar");
        Botón_Editar_Arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_Editar_ArmaActionPerformed(evt);
            }
        });
        jPanel3.add(Botón_Editar_Arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 80, 50));

        Botón_Eliminar_Arma.setText("Eliminar");
        Botón_Eliminar_Arma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_Eliminar_ArmaActionPerformed(evt);
            }
        });
        jPanel3.add(Botón_Eliminar_Arma, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 90, 50));

        Botón_ver_armas.setText("Ver datos");
        Botón_ver_armas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botón_ver_armasActionPerformed(evt);
            }
        });
        jPanel3.add(Botón_ver_armas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jTabbedPane1.addTab("Editar Arma", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ver_Personas.setEditable(false);
        Ver_Personas.setColumns(20);
        Ver_Personas.setRows(5);
        jScrollPane2.setViewportView(Ver_Personas);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 580, 170));

        jLabel15.setText("Inserte Posición");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));
        jPanel4.add(Posición, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 60, -1));

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        jPanel4.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 80, 40));

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        jPanel4.add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 80, 40));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel4.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 80, 40));

        jTabbedPane1.addTab("Editar Personas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void DesaparecidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesaparecidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesaparecidosActionPerformed

    private void dañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dañoActionPerformed

    private void Botón_armaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_armaActionPerformed
        String arma;
        float Daño;
        arma = cb_armas.getSelectedItem().toString();
        Daño = Float.parseFloat(daño.getText());
        Armas x = new Armas(arma, Daño);
        armas.add(x);
        daño.setText("");
        JOptionPane.showMessageDialog(null, "Arma ingresada correctamente");
        DefaultComboBoxModel dc
                = (DefaultComboBoxModel) cb_armas_personas.getModel();
        dc.addElement(x.getTipo());
        cb_armas_personas.setModel(dc);
    }//GEN-LAST:event_Botón_armaActionPerformed

    private void Botón_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_GuardarActionPerformed
        if (Botón_Campista.isSelected()) {
            try {

                String nombre;
                int edad;
                String sexo = "";
                Armas arma;

                String estado = "";
                String tipo_campista = "";
                nombre = Nombre.getText();
                edad = Integer.parseInt(Edad.getText());
                if (Botón_Masculino.isSelected()) {
                    sexo = "Hombre";
                } else {
                    sexo = "Mujer";
                }
                int x;
                x = cb_armas_personas.getSelectedIndex();
                arma = (armas.get(x));
                if (Botón_Vivo.isSelected()) {
                    estado = "Vivo";
                } else {
                    estado = "Desaparecido";
                }
                if (Botón_Normal.isSelected()) {
                    tipo_campista = "Normal";
                } else {
                    tipo_campista = "Supervisor";
                }
                Campistas c = new Campistas(tipo_campista, estado, nombre, edad, sexo, arma);
                personas.add(c);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Ocurrio un error y no se guardaron los datos");
            }

            JOptionPane.showMessageDialog(null, "Campista guardado exitosamente");
            Nombre.setText("");
            Edad.setText("");

        }
        if (Botón_Jason.isSelected()) {
            
            try {

                String nombre = "";
                int edad;
                String sexo = "";
                Armas arma;
                int desaparecidos;
                nombre = Nombre.getText();
                edad = Integer.parseInt(Edad.getText());
                if (Botón_Masculino.isSelected()) {
                    sexo = "Hombre";
                } else {
                    sexo = "Mujer";
                }
                int x;
                x = cb_armas_personas.getSelectedIndex();
                arma = (armas.get(x));
                desaparecidos = Integer.parseInt(Desaparecidos.getText());

                el_wapo_hockero_asesino e = new el_wapo_hockero_asesino(desaparecidos, nombre, edad, sexo, arma);
                personas.add(e);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Ocurrio un error y no se guardaron los datos");
            }
            JOptionPane.showMessageDialog(null, "Jason guardado exitosamente");
             Nombre.setText("");
            Edad.setText("");
            Desaparecidos.setText("");
        }
    }//GEN-LAST:event_Botón_GuardarActionPerformed

    private void Botón_ver_armasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_ver_armasActionPerformed
        String cadena = "";
        for (Object t : armas) {
            cadena += armas.indexOf(t) + "." + t +"\n";
        }
        Ver_Armas.setText(cadena);
    }//GEN-LAST:event_Botón_ver_armasActionPerformed

    private void Botón_Eliminar_ArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_Eliminar_ArmaActionPerformed
        int borrar;
        borrar = Integer.parseInt(Posición_Armas.getText());
        if (borrar > armas.size()) {
            JOptionPane.showMessageDialog(null, "Posición invalida");

        } else {
            armas.remove(borrar);
            String cadena = "";
            for (Object t : armas) {
                cadena += armas.indexOf(t) + "." + t + "\n";
            }
            Ver_Armas.setText(cadena);
            cb_armas_personas.removeItemAt(borrar);
        }
    }//GEN-LAST:event_Botón_Eliminar_ArmaActionPerformed

    private void Botón_Editar_ArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botón_Editar_ArmaActionPerformed
        int editar;
        editar = Integer.parseInt(Posición_Armas.getText());
        if (editar > armas.size()) {
            JOptionPane.showMessageDialog(null, "Posición invalida");

        } else {
            String arma = "";
            int ar = 0;
            do {
                ar = Integer.parseInt(JOptionPane.showInputDialog("Ingrese tipo de arma: \n 1.Hacha \n 2. pistola \n 3. bate \n 4.pala \n 5.Sierra \n 6 puños"));
            } while (ar < 0 || ar > armas.size());

            if (ar == 1) {
                arma = "Hacha";
            }
            if (ar == 2) {
                arma = "Pistola";
            }
            if (ar == 3) {
                arma = "Bate";
            }
            if (ar == 4) {
                arma = "Pala";
            }
            if (ar == 5) {
                arma = "Sierra eléctrica";
            }
            if (ar == 6) {
                arma = "Puños";
            }
            int daño1 = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el daño: "));
            Armas a = new Armas(arma, daño1);
            armas.set(editar, a);
            cb_armas_personas.insertItemAt(a.getTipo(), editar);
            String cadena = "";
            for (Object t : armas) {
                cadena += armas.indexOf(t) + "." + t + "\n";
            }
            Ver_Armas.setText(cadena);

        }
    }//GEN-LAST:event_Botón_Editar_ArmaActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        String cadena = "";
        for (Object t : personas) {
            cadena += personas.indexOf(t) + "." + t + "\n";
        }
        Ver_Personas.setText(cadena);


    }//GEN-LAST:event_MostrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int borrar;
        borrar = Integer.parseInt(Posición.getText());
        if (borrar > personas.size()) {
            JOptionPane.showMessageDialog(null, "Posición invalida");

        } else {
            personas.remove(borrar);
            String cadena = "";
            for (Object t : personas) {
                cadena += personas.indexOf(t) + "." + t + "\n";
            }
            Ver_Personas.setText(cadena);

        }    }//GEN-LAST:event_EliminarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        int editar;
        editar = Integer.parseInt(Posición.getText());
        if (editar > personas.size()) {
            JOptionPane.showMessageDialog(null, "Posición invalida");

        } else {
            
            int x = 0;
            do {
                x = Integer.parseInt(JOptionPane.showInputDialog("1- Campista \n 2- Jason \n: "));

            } while (x < 0 || x > 2);
            try {
            if (x == 1) {

                    String nombre;
                    int edad;
                    String sexo = "";
                    Armas arma;

                    String estado = "";
                    String tipo_campista = "";
                    nombre = JOptionPane.showInputDialog("Ingrese nombre: ");
                    edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese edad: "));
                    int y;
                    do {
                        y = Integer.parseInt(JOptionPane.showInputDialog("Usted es? \n 1- Hombre \n 2- Mujer \n: "));
                    } while (y < 0 || y > 2);
                    if (7 == 1) {
                        sexo = "Hombre";
                    } else {
                        sexo = "Mujer";
                    }
                    String cadena = "";
                    for (Object t : armas) {
                        cadena += armas.indexOf(t) + "." + t + "\n";
                        Ver_Personas.setText(cadena);
                    }
                    JOptionPane.showMessageDialog(null,"Mire la pantalla del programa");
                    int z;
                    do{
                    z = Integer.parseInt(JOptionPane.showInputDialog("Ingrese una arma: "));
                        
                    }while(z<0 || z>armas.size());
                            
                    arma = armas.get(z);
                    int w;
                    do{
                   w = Integer.parseInt( JOptionPane.showInputDialog("1-Vivo \n 2- Desaparecido \n : "));
                        
                    }while(w<1 || w > 2);

                    if (w==1) {
                        estado = "Vivo";
                    } else {
                        estado = "Desaparecido";
                    }
                    int m;
                    do{
                    m= Integer.parseInt( JOptionPane.showInputDialog("1-Normal \n 2- Suprevisor \n : "));
                        
                    }while(m<1 || m > 2);
                    if (m==2) {
                        tipo_campista = "Normal";
                    } else {
                        tipo_campista = "Supervisor";
                    }
                    Campistas c = new Campistas(tipo_campista, estado, nombre, edad, sexo, arma);
                    personas.set(editar,c);
            }    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrio un error y no se guardaron los datos");
                }

                JOptionPane.showMessageDialog(null, "Campista guardado exitosamente");
                 String cadena = "";
            for (Object t : personas) {
                cadena += personas.indexOf(t) + "." + t + "\n";
            }
            Ver_Personas.setText(cadena);
            if(x== 2){
                try{
                String nombre = "";
                int edad;
                String sexo = "";
                Armas arma;
                        
              nombre = JOptionPane.showInputDialog("Ingrese nombre: ");
                    edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese edad: "));
                    int y;
                    do {
                        y = Integer.parseInt(JOptionPane.showInputDialog("Usted es? \n 1- Hombre \n 2- Mujer \n: "));
                    } while (y < 0 || y > 2);
                    if (7 == 1) {
                        sexo = "Hombre";
                    } else {
                        sexo = "Mujer";
                    }
                    String cadena1 = "";
                    for (Object t : armas) {
                        cadena1 += armas.indexOf(t) + "." + t + "\n";
                        Ver_Personas.setText(cadena1);
                    }
                    JOptionPane.showMessageDialog(null,"Mire la pantalla del programa");
                    int z;
                    do{
                    z = Integer.parseInt(JOptionPane.showInputDialog("Ingrese una arma: "));
                        
                    }while(z<0 || z>armas.size());
                            
                    arma = armas.get(z); 
                    int h;
                    
                    h =Integer.parseInt(JOptionPane.showInputDialog("Ingrese cantidad de gente que ayudó a desaparecer: "));
                el_wapo_hockero_asesino b = new el_wapo_hockero_asesino(h, nombre, edad, sexo, arma);
                personas.set(editar,b);
                }catch(Exception e) {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrio un error y no se guardaron los datos");
                }
                JOptionPane.showMessageDialog(null,"Jason editado correctamente");
             String caden1 = "";
            for (Object t : personas) {
                caden1 += personas.indexOf(t) + "." + t + "\n";
            }
            Ver_Personas.setText(caden1);
            }
        }
    }//GEN-LAST:event_EditarActionPerformed

    private void cb_armas_personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_armas_personasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_armas_personasActionPerformed

    public void main() {
        initComponents();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examen1_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examen1_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examen1_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examen1_WalterReyes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examen1_WalterReyes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Botón_Campista;
    private javax.swing.JRadioButton Botón_Desaparecido;
    private javax.swing.JButton Botón_Editar_Arma;
    private javax.swing.JButton Botón_Eliminar_Arma;
    private javax.swing.JRadioButton Botón_Femenino;
    private javax.swing.JButton Botón_Guardar;
    private javax.swing.JRadioButton Botón_Jason;
    private javax.swing.JRadioButton Botón_Masculino;
    private javax.swing.JRadioButton Botón_Normal;
    private javax.swing.JRadioButton Botón_Supervisor;
    private javax.swing.JRadioButton Botón_Vivo;
    private javax.swing.JButton Botón_arma;
    private javax.swing.JButton Botón_ver_armas;
    private javax.swing.JTextField Desaparecidos;
    private javax.swing.JTextField Edad;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Posición;
    private javax.swing.JTextField Posición_Armas;
    private javax.swing.JTextArea Ver_Armas;
    private javax.swing.JTextArea Ver_Personas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cb_armas;
    private javax.swing.JComboBox<String> cb_armas_personas;
    private javax.swing.JTextField daño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
ArrayList<Armas> armas = new ArrayList();
    ArrayList<Personas> personas = new ArrayList();
}
